### ISSUE TITLE
Watch won't work on file changes

### ISSUE THREAD

**Issue by softshape** [Ceasar/staticjinja#49]
Hi all,

"staticjinja build" works fine on my setup. "staticjinja watch" starts OK but brokes right after it detects a single change in templates. The full log is -

> staticjinja watch --srcpath=D:\Work\saree.ru\redesign\templates\ --outpath=D:\Work\saree.ru\redesign\www\
Rendering K11-mint-tunic/index.html...
Rendering base.html...
Watching 'D:\Work\saree.ru\redesign\templates\' for changes...
Press Ctrl+C to stop.
modified D:\Work\saree.ru\redesign\templates\K11-mint-tunic\index.html
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Programs\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Programs\Python27\lib\site-packages\watchdog\observers\api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "C:\Programs\Python27\lib\site-packages\watchdog\observers\api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "C:\Programs\Python27\lib\site-packages\watchdog\events.py", line 322, in dispatch
    self.on_any_event(event)
  File "C:\Programs\Python27\lib\site-packages\easywatch\easywatch.py", line 25, in wrapper
    return handler(event.event_type, event.src_path)
  File "C:\Programs\Python27\lib\site-packages\staticjinja\reloader.py", line 47, in event_handler
    templates = self.site.get_dependencies(filename)
  File "C:\Programs\Python27\lib\site-packages\staticjinja\staticjinja.py", line 278, in get_dependencies
    return [self.get_template(filename)]
  File "C:\Programs\Python27\lib\site-packages\staticjinja\staticjinja.py", line 94, in get_template
    return self._env.get_template(template_name)
  File "C:\Programs\Python27\lib\site-packages\jinja2\environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Programs\Python27\lib\site-packages\jinja2\environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Programs\Python27\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Programs\Python27\lib\site-packages\jinja2\loaders.py", line 160, in get_source
    pieces = split_template_path(template)
  File "C:\Programs\Python27\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
TemplateNotFound: K11-mint-tunic\index.html

How to fix that?

**Comment by bbenne10** [comment]
I hadn't seen it until now, but this just popped up for me as well. I might be able to look into this shortly.

**Comment by bbenne10** [comment]
Ah. I think I've found it. I'll prepare a pull request. In my case, Vim is creating a shadow file for this one and then immediately deleting it (or something). Adding `os.path.isfile(filename)` to the `and` condition in `should_handle` seems to fix it.

**Comment by bbenne10** [comment]
Thanks for the quick turn around. Not needing to maintain a fork of this will really help us out at work. I appreciate the attention :)
