### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by jonathan-s** [Ceasar/staticjinja#66]
I get the following traceback. Not really sure why. 

Happens when I try the following code and I have an index.html file in templates.
```

if __name__ == '__main__':
    contexts = [
        ('.*.html', {'test': 'test'})
    ]
    site = make_site(
        contexts=contexts
    )
    site.render(use_reloader=True)
```

```
Traceback (most recent call last):
  File "performancepage.py", line 26, in <module>
    site.render(use_reloader=True)
  File "/Users/jonathan/.virtualenvs/perf/lib/python2.7/site-packages/staticjinja/staticjinja.py", line 290, in render
    self.render_templates(self.templates)
  File "/Users/jonathan/.virtualenvs/perf/lib/python2.7/site-packages/staticjinja/staticjinja.py", line 261, in render_templates
    self.render_template(template, filepath)
  File "/Users/jonathan/.virtualenvs/perf/lib/python2.7/site-packages/staticjinja/staticjinja.py", line 236, in render_template
    context = self.get_context(template)
  File "/Users/jonathan/.virtualenvs/perf/lib/python2.7/site-packages/staticjinja/staticjinja.py", line 128, in get_context
    return context_generator()
TypeError: 'dict' object is not callable
```

**Comment by Ceasar** [comment]
Ah, I need to fix the documentation to stay in sync with the latest stable version rather than master. Anyway, I just released a new version, 0.3.3 which includes the change you'll need to get that to work. Thanks for pointing this out. :+1:
